apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: drones.simulator.example.com
spec:
  group: simulator.example.com
  versions:
    - name: v1
      served: true
      storage: true
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              required: [droneID, mission]
              properties:
                droneID:
                  type: string
                  description: "Unique identifier for the drone"
                mission:
                  type: string
                  description: "Mission assigned (e.g., Recon Area A)"
                status:
                  type: string
                  enum: [pending, active, completed, failed]
                  description: "Current mission status"
            status:
              type: object
              properties:
                phase:
                  type: string
                  description: "Operator-managed phase (e.g., running, stopped)"
                podName:
                  type: string
                  description: "Name of the pod managing this drone"
  scope: Namespaced
  names:
    plural: drones
    singular: drone
    kind: Drone
    shortNames:
    - dr
